apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdc-frontend
spec:
  template:
    spec:
      containers:
        - name: vdc-frontend
          image: ghcr.io/moravianlibrary/vdc-frontend:latest