apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdc-frontend-public
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: vdc-frontend-public
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vdc-frontend-public
        app.kubernetes.io/name: vdc-frontend-public
    spec:
      containers:
        - name: vdc-frontend-public
          image: mzk.cz/vdc-frontend-public
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: vdc-frontend-env-config
      imagePullSecrets:
        - name: pull-secret
