apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdc-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: vdc-api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vdc-api
        app.kubernetes.io/name: vdc-api
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000  
      initContainers:
        - name: chown-container
          image: busybox:latest
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command: ["sh","-c","chown -R 1000:1000 /app/data"]
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: app-data
              mountPath: /app/data
      containers:
        - name: vdc-api
          image: mzk.cz/vdc-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: vdc-api-env-config
          volumeMounts:
            - name: app-data
              mountPath: /app/data              
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data
            readOnly: false      
      imagePullSecrets:
        - name: pull-secret