apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdc-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: vdc-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vdc-frontend
        app.kubernetes.io/name: vdc-frontend
    spec:     
      containers:
        - name: vdc-frontend
          image: mzk.cz/vdc-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: vdc-frontend-env-config     
      imagePullSecrets:
        - name: pull-secret